server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/artlabledb
    username: artadmin
    password: artadmin

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    show-sql: true

  data.rest:
    base-path: /api
    detection-strategy: annotated

  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

jwt:
  secret: secret:60aab420e438f79d48594b03eaaf4ddebd2515f7a862807695ab253d75ae8e10cc85a164f612210a0e9500684d890b7ce862efd4fa11b195ba7cfd0fad86c472
